name: Terisk CI test and deploy

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli:  latest     # Clojure CLI based on tools.deps

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'timothypratley/terisk'
        env:
          CLOJARS_PASSWORD: ${{ secrets.CLOJARSTOKEN }}
          CLOJARS_USERNAME: timothypratley
        run: make deploy
